import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { CatalogueControls } from "@/components/catalogue/catalogue-controls";
import { Pagination } from "@/components/catalogue/pagination";
import { ProductCard } from "@/components/catalogue/product-card";
import { getCategories, getProducts } from "@/lib/catalogue";

type Props = { params: Promise<{ slug: string }>; searchParams: Promise<Record<string, string | string[] | undefined>> };
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { slug } = await params; const category = (await getCategories()).find(item => item.slug === slug); if (!category) return {}; const title = category.seoTitle || category.name; return { title, description: category.seoDescription || category.description || `Browse ${category.name.toLowerCase()} for generator maintenance and repair.`, alternates: { canonical: `/categories/${slug}` } }; }
export default async function CategoryPage({ params, searchParams }: Props) { const [{ slug }, raw] = await Promise.all([params, searchParams]); const category = (await getCategories()).find(item => item.slug === slug); if (!category) notFound(); const search = Object.fromEntries(Object.entries(raw).map(([key, value]) => [key, Array.isArray(value) ? value[0] : value])); const sort = search.sort === "name" || search.sort === "latest" ? search.sort : "featured"; const result = await getProducts({ ...search, category: slug, sort, page: Number(search.page) || 1, pageSize: 24 }); const categories = await getCategories();
  return <div className="page shell"><nav className="breadcrumbs" aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><Link href="/categories">Categories</Link><span>/</span><span>{category.name}</span></nav><header className="category-hero"><div><p className="eyebrow">Generator system</p><h1>{category.name}</h1><p>{category.description}</p><strong>{category.productCount} catalogue components</strong></div>{category.image && <Image src={category.image} alt={category.imageAlt || category.name} width={500} height={360} />}</header><CatalogueControls categories={categories} /><p className="results-count">{result.total} components in {category.name}</p><div className="product-grid catalogue-grid">{result.items.map(product => <ProductCard product={product} key={product.id} />)}</div><Pagination total={result.total} page={result.page} pageSize={result.pageSize} pathname={`/categories/${slug}`} search={search} /><section className="category-support"><p className="eyebrow">Need help identifying a component?</p><h2>Share your generator details.</h2><p>Provide a part number, manufacturer, generator model or reference photo and the IGP team can review your request.</p><Link className="button button-primary" href="/request-quote">Request identification <span aria-hidden="true">↗</span></Link></section></div>;
}
