import Image from "next/image";
import Link from "next/link";
import { CategoryCard } from "@/components/catalogue/category-card";
import { ProductCard } from "@/components/catalogue/product-card";
import { getCategories, getProducts } from "@/lib/catalogue";

export default async function HomePage() {
  const [categories, featured] = await Promise.all([getCategories(), getProducts({ sort: "featured", pageSize: 4 })]);
  return <><section className="hero"><Image src="/assets/generator-hero.webp" alt="Industrial generator engine in a facility" fill priority sizes="100vw" className="hero-image" /><div className="hero-overlay" /><div className="shell hero-content"><p className="eyebrow inverse">Innovative Generator Parts</p><h1>Dependable parts.<br /><span>Dependable power.</span></h1><p>Generator components for maintenance, repair and reliable operation across eight major systems.</p><div className="button-row"><Link className="button button-primary" href="/products">Browse parts <span aria-hidden="true">↗</span></Link><Link className="button button-light" href="/request-quote">Request a quote</Link></div></div></section>
    <section className="trust-bar"><div className="shell"><span>80 catalogue components</span><span>8 generator systems</span><span>Part identification support</span></div></section>
    <section className="section shell part-finder"><div><p className="eyebrow">Find the right component</p><h2>Start with the part<br />or the system.</h2></div><form action="/products" className="finder-search"><label className="sr-only" htmlFor="home-search">Search the catalogue</label><input id="home-search" name="query" type="search" placeholder="Search AVR, radiator, fuel pump…" /><button className="button button-primary">Search <span aria-hidden="true">→</span></button></form></section>
    <section className="section section-tint"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Featured categories</p><h2>Generator systems<br />at a glance.</h2></div><Link href="/categories" className="text-link">Explore all systems <span>→</span></Link></div><div className="category-grid">{categories.map((category, index) => <CategoryCard category={category} index={index} key={category.id} />)}</div></div></section>
    <section className="section shell"><div className="section-heading"><div><p className="eyebrow">Featured components</p><h2>Key parts for<br />generator maintenance.</h2></div><Link href="/products" className="text-link">Browse catalogue <span>→</span></Link></div><div className="product-grid">{featured.items.map(product => <ProductCard product={product} key={product.id} />)}</div></section>
    <section className="statement"><div className="shell"><p className="eyebrow inverse">Built around reliable power</p><h2>Every part matters when<br /><span>power cannot wait.</span></h2><p>IGP brings core generator systems together in one structured catalogue, so customers can identify the component they need and request help when the exact part is uncertain.</p><Link href="/about" className="button button-light">About IGP</Link></div></section>
    <section className="section shell split-section"><div><p className="eyebrow">Technical reference</p><h2>More than a<br />parts list.</h2><p>Working principles and daily-use descriptions help make each component easier to identify.</p></div><div className="education-list"><article><h3>Automatic Voltage Regulator</h3><p>Monitors voltage and adjusts excitation to maintain stable output voltage.</p><Link href="/products/electrical-alternator-avr">View component <span>→</span></Link></article><article><h3>Turbocharger</h3><p>Uses exhaust energy to compress intake air and improve combustion efficiency.</p><Link href="/products/air-exhaust-turbocharger">View component <span>→</span></Link></article><article><h3>Thermostat</h3><p>Opens and closes according to coolant temperature to maintain operation.</p><Link href="/products/cooling-system-thermostat">View component <span>→</span></Link></article></div></section>
    <section className="cta-band"><div className="shell"><p className="eyebrow inverse">Part identification support</p><h2>Not sure which<br />part you need?</h2><p>Share your generator brand, model, part number or reference image. The IGP team can review the details you provide.</p><Link className="button button-primary" href="/request-quote">Identify a part <span aria-hidden="true">↗</span></Link></div></section>
  </>;
}
