import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ProductCard } from "@/components/catalogue/product-card";
import { getProductBySlug, getRelatedProducts } from "@/lib/catalogue";
import { appUrl } from "@/lib/utils";

type Props = { params: Promise<{ slug: string }> };
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { slug } = await params; const product = await getProductBySlug(slug); if (!product) return {}; const title = product.seoTitle || product.name; const description = product.seoDescription || product.shortDescription || product.dailyUse; return { title, description, alternates: { canonical: `/products/${product.slug}` }, openGraph: { title, description, images: product.image ? [{ url: product.image, alt: product.imageAlt || product.name }] : [] } }; }
export default async function ProductPage({ params }: Props) { const { slug } = await params; const product = await getProductBySlug(slug); if (!product) notFound(); const related = await getRelatedProducts(product); const schema = { "@context": "https://schema.org", "@graph": [{ "@type": "Product", name: product.name, description: product.shortDescription || product.dailyUse, image: product.image ? [appUrl(product.image)] : undefined, category: product.category.name, url: appUrl(`/products/${product.slug}`) }, { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: appUrl("/") }, { "@type": "ListItem", position: 2, name: product.category.name, item: appUrl(`/categories/${product.category.slug}`) }, { "@type": "ListItem", position: 3, name: product.name, item: appUrl(`/products/${product.slug}`) }] }] };
  return <div className="page shell"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /><nav className="breadcrumbs" aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><Link href={`/categories/${product.category.slug}`}>{product.category.name}</Link><span>/</span><span>{product.name}</span></nav><article className="product-detail"><div className="product-detail-image">{product.image ? <Image src={product.image} alt={product.imageAlt || product.name} fill unoptimized sizes="(max-width: 800px) 100vw, 50vw" priority /> : <span>IGP</span>}</div><div><p className="eyebrow">{product.category.name}</p><h1>{product.name}</h1><p className="product-lead">{product.shortDescription || product.dailyUse}</p><dl className="product-facts"><div><dt>Working principle</dt><dd>{product.workingPrinciple}</dd></div><div><dt>Daily use</dt><dd>{product.dailyUse}</dd></div>{product.manufacturer && <div><dt>Manufacturer</dt><dd>{product.manufacturer}</dd></div>}{product.partNumber && <div><dt>Part number</dt><dd>{product.partNumber}</dd></div>}</dl><Link href={`/request-quote?product=${encodeURIComponent(product.slug)}`} className="button button-primary">Request a quote <span aria-hidden="true">↗</span></Link></div></article>{related.length > 0 && <section className="related section"><div className="section-heading"><div><p className="eyebrow">Related components</p><h2>Explore this system.</h2></div><Link className="text-link" href={`/categories/${product.category.slug}`}>View {product.category.name} <span>→</span></Link></div><div className="product-grid">{related.map(item => <ProductCard product={item} key={item.id} />)}</div></section>}</div>;
}
